Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 100

SignalException:
  EnforcedStyle: only_raise

# Disabled, see bbatsov/rubocop#1633
Style/MultilineOperationIndentation:
  Enabled: false

TrailingComma:
  Enabled: false
